[General]
DisplayServer=x11

[Autologin]
Relogin=false
Session=
User=

[Theme]
Current=mika-mono
CursorSize=24
CursorTheme=capitaine-cursors
Font=JetBrainsMono Nerd Font

[Users]
MaximumUid=60513
MinimumUid=1000
RememberLastSession=true
RememberLastUser=true
