wallpaper {
    monitor = DP-1
    path = /home/mika/System/dotfiles/.config/hypr/wallpapers/wallhaven-og61yl_1920x1080.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/mika/System/dotfiles/.config/hypr/wallpapers/wallhaven-og61yl_1920x1080.png
    fit_mode = cover
}

splash = false
ipc = true
